/* 30_mente_sana.yaml  —  capa mente_sana  (MS)
   Capa 3 — Módulo Mente Sana (transición primaria-secundaria). Reusa el núcleo (IE x Nivel via core_ie.cod_unico) y el motor de instrumentos. Agrega el módulo propio Estudiante (observación de habilidades) que CCA no tiene.
   Schema: efectoancash · Motor: postgres · generado por build.py — no editar a mano. */

CREATE SCHEMA IF NOT EXISTS efectoancash;
SET search_path TO efectoancash, public;

/* -- ms_roster -- Roster por IE/Nivel/Grado (MS distingue primaria y secundaria). */

CREATE TABLE IF NOT EXISTS efectoancash.ms_roster (
  id int generated by default as identity PRIMARY KEY,
  ie_id int NOT NULL,
  grado varchar(20),
  persona_id int,
  apellidos_nombres varchar(200),
  activo boolean DEFAULT true
);

COMMENT ON TABLE efectoancash.ms_roster IS 'Roster por IE/Nivel/Grado (MS distingue primaria y secundaria).';

/* -- ms_sesion -- Sesión ejecutada (Reporte al día). Incluye Asist_Estudiantes (propio de MS). */

CREATE TABLE IF NOT EXISTS efectoancash.ms_sesion (
  id int generated by default as identity PRIMARY KEY,
  core_sesion_id int,
  ie_id int NOT NULL,
  grado varchar(20),
  etapa_id int,
  tema varchar(200),
  asist_estudiantes int DEFAULT 0,
  asist_familias int DEFAULT 0,
  asist_docentes int DEFAULT 0,
  asist_otros_cant int DEFAULT 0,
  asist_otros_texto varchar(120),
  desarrollo text,
  incidencia_sn boolean DEFAULT false,
  descripcion_incidencia text
);

COMMENT ON TABLE efectoancash.ms_sesion IS 'Sesión ejecutada (Reporte al día). Incluye Asist_Estudiantes (propio de MS).';

/* -- ms_asistencia -- Asistencia persona x sesión (mismo patrón que CCA). */

CREATE TABLE IF NOT EXISTS efectoancash.ms_asistencia (
  id bigint generated by default as identity PRIMARY KEY,
  ms_sesion_id int NOT NULL,
  roster_id int NOT NULL,
  asistio boolean DEFAULT false
);

COMMENT ON TABLE efectoancash.ms_asistencia IS 'Asistencia persona x sesión (mismo patrón que CCA).';

/* -- ms_evaluacion_estudiante -- Módulo propio MS: observación de habilidades (Bloq_1..5 + conductas) por corte. */

CREATE TABLE IF NOT EXISTS efectoancash.ms_evaluacion_estudiante (
  id int generated by default as identity PRIMARY KEY,
  ie_id int NOT NULL,
  grado varchar(20),
  seccion varchar(10),
  persona_id int,
  intento_id int,
  lenguaje_corporal varchar(20),
  contacto_visual varchar(20),
  tono_volumen_voz varchar(20),
  tiempo_reaccion varchar(20),
  interaccion_material varchar(20),
  conducta_social varchar(20),
  comentario text
);

COMMENT ON TABLE efectoancash.ms_evaluacion_estudiante IS 'Módulo propio MS: observación de habilidades (Bloq_1..5 + conductas) por corte.';
COMMENT ON COLUMN efectoancash.ms_evaluacion_estudiante.intento_id IS 'corte + IE + facilitador';

CREATE INDEX IF NOT EXISTS ix_ms_asist_sesion ON efectoancash.ms_asistencia (ms_sesion_id);

CREATE INDEX IF NOT EXISTS ix_ms_roster_ie ON efectoancash.ms_roster (ie_id, grado);
